### ISSUE TITLE
Scenarios of sending email as notifications

### ISSUE THREAD

**Issue by superopengl** [eztax-io/eztax-app#28]
At below timing, we should send mail as notifications

As a user (either client or agent),
- signup.
- requests reset the password.
- has reset the password.
- receives a message (new message in inbox)

As a client
- his/her lodgment status changes

As an agent
- his/her status changes (unverified => verified, verified => suspended, suspended => verified)

As a guest
- his/her contact has been sent

**Comment by luacolin** [comment]
I think that covers most of the scenarios for now. :)
